### ISSUE TITLE
News, board member schema, importers

### ISSUE THREAD

**Issue by hampelm** [detroitledger/gnl-graphql#12]
exports: https://data.detroitledger.org/profiles/gnl_profile/exporters/person.json https://data.detroitledger.org/profiles/gnl_profile/exporters/news.json https://data.detroitledger.org/profiles/gnl_profile/exporters/board_term.json

**Comment by bnchdrff** [comment]
@hampelm take note i just updated those export jsons - they were limited to 100 entries, now they have everything
