### ISSUE TITLE
Orgs without EINs get an EIN of 0 (zero)

### ISSUE THREAD

**Issue by hampelm** [detroitledger/gnl-graphql#27]
Organizations that do not have an EIN are getting assigned a "0" EIN when imported. Instead, they should be NULL. 

This also makes me worry that we are treating EINs as numbers at some point in the import process, even though the type is `varchar`. We might be losing leading zeros on import.

**Comment by hampelm** [comment]
I set the existing zeros to null in the Heroku DB as a stopgap

```
update organization 
set ein = null
where ein = '0';
```

**Comment by bnchdrff** [comment]
are leading zeros important for eins?

**Comment by bnchdrff** [comment]
i think we should be normalizing them to exclude leading zeros and any dashes also

**Comment by hampelm** [comment]
I think we should keep EINs in the official format as provided by the IRS as much as possible, and not strip anything. In my experience things like leading zeros suck but are important for consistency.

https://www.irs.gov/pub/irs-pdf/p1635.pdf

> An Employer Identification Number (EIN) is a nine-digit number that IRS assigns
in the following format: XX-XXXXXXX. It is used to identify the tax accounts of employers and certain others who have no employees. However, for employee plans,
an alpha (for example, P) or the plan number (e.g., 003) may follow the EIN. The IRS
uses the number to identify taxpayers that are required to file various business tax
returns. EINs are used by employers, sole proprietors, corporations, partnerships,
non-profit associations, trusts, estates of decedents, government agencies, certain
individuals, and other business entities. Use your EIN on all of the items that you
send to the IRS and the Social Security Administration (SSA)

**Comment by bnchdrff** [comment]
in our old db we store them as nullable integers, so any leading zeros are not present in our source data.

**Comment by bnchdrff** [comment]
in the current `form_990` dataset we have EINs left-padded with 0s but none contain the dash

**Comment by hampelm** [comment]
Yeah, that's how they come from the IRS exports

**Comment by bnchdrff** [comment]
cool; i'll set up a migration to left-pad where needed, as well as modify the importer for posterity

**Comment by hampelm** [comment]
Sweet. I think that'll help us in the long run (until of course I accidentally parse an EIN as a number)

**Comment by bnchdrff** [comment]
this might be a good case to use the sequelize orm-level validation, so when we can share a validator for eins in both the organization and form 990 tables (and wherever else)

**Comment by bnchdrff** [comment]
k, added a migration that runs @hampelm's cleanup as well as a 0 left pad.
