### ISSUE TITLE
Peer dependency warnings on install

### ISSUE THREAD

**Issue by hampelm** [detroitledger/gnl-graphql#6]
Installing with yarn works; npm fails; yarn gives these warnings: 

```warning "react-apollo@0.8.1" has incorrect peer dependency "apollo-client@^0.6.0".
warning "eslint-config-airbnb@13.0.0" has unmet peer dependency "eslint-plugin-jsx-a11y@^2.2.3".
```

**Comment by bnchdrff** [comment]
i don't get a failure with `npm install`, just warnings that don't impact usage -- what version are you using?

**Comment by bnchdrff** [comment]
(i'm testing with latest stable vers node 7.4.0 and npm 4.0.5)

**Comment by hampelm** [comment]
I was using node 4. I'm up and running with yarn on node 7.4. haven't tried with npm again.
